ccflags-y += -I$(srctree)/drivers/misc/mediatek/base/power/$(MTK_PLATFORM)/
include $(srctree)/drivers/misc/mediatek/Makefile.custom
# Provide an interface to boost cpu hotplug and dvfs by event
obj-y += dynamic_boost.o
